package com.sky.game.service.persistence;

import com.sky.game.service.domain.ChannelItems;

public interface ChannelItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_items
     *
     * @mbggenerated
     */
    int insert(ChannelItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_items
     *
     * @mbggenerated
     */
    int insertSelective(ChannelItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_items
     *
     * @mbggenerated
     */
    ChannelItems selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_items
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChannelItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_items
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChannelItems record);
    /**
     * 根据channel_id 查询channel_items
     */
    ChannelItems selectByChannelId(long channelId);
}