package com.sky.game.service.persistence;

import com.sky.game.service.domain.ChannelExchangeInfo;

public interface ChannelExchangeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_exchange_info
     *
     * @mbggenerated
     */
    int insert(ChannelExchangeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_exchange_info
     *
     * @mbggenerated
     */
    int insertSelective(ChannelExchangeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_exchange_info
     *
     * @mbggenerated
     */
    ChannelExchangeInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_exchange_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChannelExchangeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_exchange_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChannelExchangeInfo record);
}