package com.sky.game.service.persistence;

import java.util.List;

import com.sky.game.service.domain.Exchange;
import com.sky.game.service.domain.GoldExchange;
import com.sky.game.service.domain.Goods;
import com.sky.game.service.domain.PriceExchange;

public interface ExchangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated
     */
    int insert(Exchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated
     */
    int insertSelective(Exchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated
     */
    Exchange selectByPrimaryKey(Long id);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Exchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Exchange record);
    /**
     *  奖品对换列表
     * @mbggenerated
     */
    List<PriceExchange> selectPriceExchange(long channelItemId);
    /**
     *  查询所需要的物品数
     *  
     * @mbggenerated
     */
    int selectPrice(long id);
    /**
     * 物品对换
     */
    List<Goods> selectItemGoods(long userId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated
     */
    int selectResDay(long id);
    /*
     * 查询金币对换列表
     */
    List<GoldExchange> selectItemGold();
    /**
     * 查询一列信息根据id
     * @return
     */
    Exchange selectInfoById(long id);
}