package com.sky.game.service.persistence;

import java.util.List;

import com.sky.game.service.domain.ExchangeLog;
import com.sky.game.service.domain.ExchangeRecord;

public interface ExchangeLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_trade_log
     *
     * @mbggenerated
     */
    int insert(ExchangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_trade_log
     *
     * @mbggenerated
     */
    int insertSelective(ExchangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_trade_log
     *
     * @mbggenerated
     */
    ExchangeLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_trade_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExchangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_trade_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExchangeLog record);
    
    
    void insertExchangeLog(ExchangeLog record);
    
    List<ExchangeRecord> selectExchangeRecord();
}