package com.sky.game.service.persistence;

import java.util.HashMap;
import java.util.List;

import com.sky.game.service.domain.Freeze;

public interface FreezeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freeze
     *
     * @mbggenerated
     */
    int insert(Freeze record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freeze
     *
     * @mbggenerated
     */
    int insertSelective(Freeze record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freeze
     *
     * @mbggenerated
     */
    Freeze selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freeze
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Freeze record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freeze
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Freeze record);
    
    /**
     *  查询冻结表中的所有数据
     */
    Freeze selectFreeze(HashMap<String,Object> hashmap);
    
    /**
     *  查询冻结表中的所有数据    修改 2015-3-17
     */
    Freeze selectFreezeUpdate(HashMap<String,Object> hashmap);
    
    /*
     * 根据pointCardId 查询freeze 列表
     */
    List<Freeze> selectByPointId(long pointCardId);
    /**
     * 根据id 删除记录
     */
    int deleteByPointId(long id);
}