package com.sky.game.service.persistence;

import com.sky.game.service.domain.GameBlockadeLog;

public interface GameBlockadeLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_blockade_log
     *
     * @mbggenerated
     */
    int insert(GameBlockadeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_blockade_log
     *
     * @mbggenerated
     */
    int insertSelective(GameBlockadeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_blockade_log
     *
     * @mbggenerated
     */
    GameBlockadeLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_blockade_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GameBlockadeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_blockade_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GameBlockadeLog record);
}