package com.sky.game.service.persistence;

import java.util.HashMap;
import java.util.List;

import com.sky.game.service.domain.GameBlockadeUser;

public interface GameBlockadeUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_blockade_user
     *
     * @mbggenerated
     */
    int insert(GameBlockadeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_blockade_user
     *
     * @mbggenerated
     */
    int insertSelective(GameBlockadeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_blockade_user
     *
     * @mbggenerated
     */
   

    GameBlockadeUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_blockade_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GameBlockadeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_blockade_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GameBlockadeUser record);
    /**
     * find the GameBlockadeUser 
     * @param id
     * @param roomId
     * @return
     */
    GameBlockadeUser selectByUserIdAndRoomId(Long userId,Long roomId);
    
    
    List<GameBlockadeUser>  selectByRoomIdAndLevel(Long roomId,Long level);
    
    /*
     * 积分卡合成   根据用户查询 gameblockadeuser 表
     */
   GameBlockadeUser selectByUserId(HashMap<String,Object> hashmap);
   /**
    * 积分卡合成 后删除用户所携带的积分
    */
   int deleteById(long id); 
   /**
    * 积分卡合成使用  积分卡
    */
   int updateFenAndLevel(HashMap<String,Object> hashmap);
   
   /**
    * update the current user blockade game status.
    * @param id
    * @param status
    * @return
    */
   int  updateStatus(Long id,Integer status);
   
   Long selectByRoomAndLevel(Long roomId,Long level);
}