package com.sky.game.service.persistence;

import com.sky.game.service.domain.GameBlockadeMessage;

public interface GameBlockadeMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_blockade_message
     *
     * @mbggenerated
     */
    int insert(GameBlockadeMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_blockade_message
     *
     * @mbggenerated
     */
    int insertSelective(GameBlockadeMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_blockade_message
     *
     * @mbggenerated
     */
    GameBlockadeMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_blockade_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GameBlockadeMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_blockade_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GameBlockadeMessage record);
}