package com.sky.game.service.persistence;

import java.util.HashMap;
import java.util.List;

import com.sky.game.service.domain.GameReward;

public interface GameRewardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_reward
     *
     * @mbggenerated
     */
    int insert(GameReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_reward
     *
     * @mbggenerated
     */
    int insertSelective(GameReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_reward
     *
     * @mbggenerated
     */
    GameReward selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_reward
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GameReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_reward
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GameReward record);
    /**
     * 夺宝明星
     * @return
     */
    List<GameReward> selectIS();
    /**
     * 个人中心奖状墙
     */
    List<GameReward> selectUserReward(HashMap<String,Object> hashmap);
}