package com.sky.game.service.persistence;

import com.sky.game.service.domain.Icon;

public interface IconMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table icon
     *
     * @mbggenerated
     */
    int insert(Icon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table icon
     *
     * @mbggenerated
     */
    int insertSelective(Icon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table icon
     *
     * @mbggenerated
     */
    Icon selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table icon
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Icon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table icon
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Icon record);
}