package com.sky.game.service.persistence;

import java.util.HashMap;
import java.util.List;

import com.sky.game.service.domain.ItemCount;

public interface ItemCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_count
     *
     * @mbggenerated
     */
    int insert(ItemCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_count
     *
     * @mbggenerated
     */
    int insertSelective(ItemCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_count
     *
     * @mbggenerated
     */
    ItemCount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_count
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ItemCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_count
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ItemCount record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_count
     *
     * @mbggenerated
     */
    void decResCount(long id);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_count
     *
     * @mbggenerated
     */
    void updateReceiveItemCount(long itmeId);
    void addReceiveItemCount(long itmeId);
    
    ItemCount selectPriceByMap(long itemId);
    
    
    int updateLeftCount(long itemId);
    
    int selectResDay(long id);
    /**
     * 查询所有itemCount
     * @see com.sky.game.service.persistence.selectAllItemCount.xml
     * @return
     */
    List<ItemCount> selectAllItemCount();
    /**
     * 修改今日投放量
     * @see com.sky.game.service.persistence.updateTodayNum.xm;
     * @return
     */
    int updateTodayNum(HashMap<String,Object> hashmap);
}