package com.sky.game.service.persistence;

import java.util.List;

import com.sky.game.service.domain.MatchCheck;

public interface MatchCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_check
     *
     * @mbggenerated
     */
    int insert(MatchCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_check
     *
     * @mbggenerated
     */
    int insertSelective(MatchCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_check
     *
     * @mbggenerated
     */
    MatchCheck selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_check
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MatchCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_check
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MatchCheck record);
    
    /*
     * 个人中心。奖状墙
     */
    List<MatchCheck> selectMatchCheckByUserId(long userId);
    /*
     * 今日之星   查询所有match-check 中的数据
     */
    List<MatchCheck> selectAllMatchCheck();
}