package com.sky.game.service.persistence;

import java.util.HashMap;
import com.sky.game.service.domain.PointCardAttribute;

public interface PointCardAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_card_attribute
     *
     * @mbggenerated
     */
    PointCardAttribute selectByPrimaryKey(Long typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_card_attribute
     *
     * @mbggenerated
     */
    /**
     * 查询所有积分卡属性
     */
    PointCardAttribute selectAll(HashMap<String,Object> hashmap);
}