package com.sky.game.service.persistence;

import java.util.List;

import com.sky.game.service.domain.AwardRecord;
import com.sky.game.service.domain.ReceiveInfo;

public interface ReceiveInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_info
     *
     * @mbggenerated
     */
    int insert(ReceiveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_info
     *
     * @mbggenerated
     */
    int insertSelective(ReceiveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_info
     *
     * @mbggenerated
     */
    ReceiveInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReceiveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReceiveInfo record);
    
    List<AwardRecord> selectAllRewardPrice(long userId);
}