package com.sky.game.service.persistence;

import java.util.List;

import com.sky.game.service.domain.Reward;

public interface RewardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    int insert(Reward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    int insertSelective(Reward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    Reward selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Reward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Reward record);
    
    int selectRewardValue(long id);
    
    /*
     * 查询所有Reward
     */
    List<Reward> selectAllReward();
    
    Reward selectTaskReward(long id);
    
}