package com.sky.game.service.persistence;

import java.util.List;

import com.sky.game.service.domain.Store;
import com.sky.game.service.domain.StoreShow;

public interface StoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated
     */
    int insert(Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated
     */
    int insertSelective(Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated
     */
    /*
     * 根据列表id查询一条购买 的记录
     */
    Store selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Store record);
    /*
     * 查询购买表中的所有数据
     */
    List<StoreShow> selectAllStore();
   
    /*int selectTotalCount(long id);
    
    int selectGiftGold(long id);
    
    int selectGiftVip(long id);
    
    
    int selectPrice(long id);*/
    
    
}