package com.sky.game.service.persistence;

import java.util.HashMap;
import java.util.List;

import com.sky.game.service.domain.Store;
import com.sky.game.service.domain.StoreOrder;

public interface StoreOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_order
     *
     * @mbggenerated
     */
    int insert(StoreOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_order
     *
     * @mbggenerated
     */
    int insertSelective(StoreOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_order
     *
     * @mbggenerated
     */
    StoreOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StoreOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StoreOrder record);
    /**
     * 去掉重复的回调数据
     * @param orderId
     * @return
     */
    StoreOrder distinctStoreOrder(String orderId);
    /**
     * 修改stroe_order status
     * @param orderId
     * @return
     */
    int updateStoreOrderStatus(String orderId);
    
    
    void insertStoreOrder(HashMap<String,Object> map);
    
    StoreOrder selectByTradeNum(String tradeNum);
    
    int updateTradeStatus(HashMap<String,Object> map);
    
    List<StoreOrder> selectAllNoOrder();
    
}