package com.sky.game.service.persistence;

import java.util.HashMap;
import java.util.List;

import com.sky.game.service.domain.SystemGiftBag;

public interface SystemGiftBagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_gift_bag
     *
     * @mbggenerated
     */
    int insert(SystemGiftBag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_gift_bag
     *
     * @mbggenerated
     */
    int insertSelective(SystemGiftBag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_gift_bag
     *
     * @mbggenerated
     */
    SystemGiftBag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_gift_bag
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemGiftBag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_gift_bag
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemGiftBag record);
    /*
     * 根据cardId 查询所有礼包和礼物
     */
    List<SystemGiftBag> selectAllByCardId(HashMap<String,Object> hashmap);
    
    /*
     * 根据id 修改system_gift-bag 的状态 
     */
    int updateSystemGiftBagState(long id);
}