package com.sky.game.service.persistence;

import java.util.List;

import com.sky.game.service.domain.SysMessage;
import com.sky.game.service.domain.SystemMessage;

public interface SystemMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbggenerated
     */
    int insert(SystemMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbggenerated
     */
    int insertSelective(SystemMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbggenerated
     */
    SystemMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemMessage record);
    
    List<SysMessage> selectMessage(long userId);
    
    long selectDecId(long userId);
}