package com.sky.game.service.persistence;

import java.util.List;

import com.sky.game.service.domain.SystemChargeItems;

public interface SystemChargeItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_charge_items
     *
     * @mbggenerated
     */
    int insert(SystemChargeItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_charge_items
     *
     * @mbggenerated
     */
    int insertSelective(SystemChargeItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_charge_items
     *
     * @mbggenerated
     */
    SystemChargeItems selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_charge_items
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemChargeItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_charge_items
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemChargeItems record);
    /**
     * 查询充值卡对应的所有物品
     * @param chargeCardAttributeId
     * @return
     */
    List<SystemChargeItems> selectAllItems(long chargeCardAttributeId);
}