package com.sky.game.service.persistence;

import com.sky.game.service.domain.SystemMssage;

public interface SystemMssageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbggenerated
     */
    int insert(SystemMssage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbggenerated
     */
    int insertSelective(SystemMssage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbggenerated
     */
    SystemMssage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemMssage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemMssage record);
}