package com.sky.game.service.persistence;

import com.sky.game.service.domain.SystemHead;

public interface SystemHeadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_head
     *
     * @mbggenerated
     */
    int insert(SystemHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_head
     *
     * @mbggenerated
     */
    int insertSelective(SystemHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_head
     *
     * @mbggenerated
     */
    SystemHead selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_head
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_head
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemHead record);
}