package com.sky.game.service.persistence;

import java.util.HashMap;

import com.sky.game.service.domain.UserToken;

public interface UserTokenMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_token
	 *
	 * @mbggenerated
	 */
	int insert(UserToken record);

	/**
	 * 
	 * 
	 * @param userId
	 * @return
	 */
	int insertToken(Long userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_token
	 *
	 * @mbggenerated
	 */
	int insertSelective(UserToken record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_token
	 *
	 * @mbggenerated
	 */
	UserToken selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_token
	 *
	 * @mbggenerated
	 */
	UserToken selectByUserId(Long userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_token
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(UserToken record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_token
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(UserToken record);

	int updateToken(HashMap<String, Object> map);
}