package com.sky.game.service.persistence;

import java.util.HashMap;
import java.util.List;

import com.sky.game.service.domain.UserAccount;

public interface UserAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbggenerated
     */
    int insert(UserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbggenerated
     */
    int insertSelective(UserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbggenerated
     */
    UserAccount selectByPrimaryKey(String account);
    
    /*
     * 根据账号id 查询账号
     */
    UserAccount selectByPrimaryId(long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserAccount record);
    
    /**
     * 
     * 
     * @param account
     * @return
     */
    UserAccount selectByAccount(String account);
    /**
     * 
     * 
     * @param account
     * @return
     */
    UserAccount selectByNP(UserAccount record);
    /*
     * 查询所有帐号
     */
    List<UserAccount> selectAll();
    /*
     * 查询所有个人的所有属性方法
     */
    
    void updateByTime(String account);
    /* 
     * 个人中心修改密码
     * */        
    int updateUserPassword(HashMap<String ,Object> hashmap);
    
    String selectNick(long userId);
    
    /**
     * 用户登录判断账号是否存在
     */
    UserAccount selectUserAccountByName(String account);
    /**
     * 根据设备号查询用户
     * 
     */
    UserAccount selectByDeviceId(String deviceId);
    /**
     * 正式用户登录时修改设备号  device_id
     */
    int updateDeviceId(HashMap<String,Object> hashmap);
}