package com.sky.game.service.persistence;

import java.util.HashMap;
import java.util.List;

import com.sky.game.service.domain.TaskState;
import com.sky.game.service.domain.UserReward;

public interface UserRewardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_reward
     *
     * @mbggenerated
     */
    int insert(UserReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_reward
     *
     * @mbggenerated
     */
    int insertSelective(UserReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_reward
     *
     * @mbggenerated
     */
    UserReward selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_reward
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_reward
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserReward record);
    
    void updateNeckType(HashMap<String,Object> map);
    
    List<TaskState> selectNeckType1(long userId);
    List<TaskState> selectNeckType2(long userId);
    
    UserReward selectByUserId(HashMap<String,Object> map);
    
    void insertUserReward(HashMap<String,Object> map);
    List<TaskState> selectNeckType3(long userId);
    
    UserReward selectRewardState(HashMap<String,Object> map);
    
    void updateRewardType(HashMap<String,Object> map);
    
}