package com.sky.game.service.persistence;

import java.util.List;

import com.sky.game.service.domain.UserLottery;

public interface UserLotteryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_lottery
     *
     * @mbggenerated
     */
    int insert(UserLottery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_lottery
     *
     * @mbggenerated
     */
    int insertSelective(UserLottery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_lottery
     *
     * @mbggenerated
     */
    UserLottery selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_lottery
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserLottery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_lottery
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserLottery record);
    
    void insertLotteryCount(long userId);
    
    void updateLotteryCount(long userId);
    
    UserLottery selectLotteryCount(long userId);
    
    void updateLotteryTiming();
    
    List<UserLottery> selectUserLottery();
    
}