package com.sky.game.service.persistence;

import java.util.HashMap;
import java.util.List;

import com.sky.game.service.domain.UserReportLog;

public interface UserReportLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_report_log
     *
     * @mbggenerated
     */
    int insert(UserReportLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_report_log
     *
     * @mbggenerated
     */
    int insertSelective(UserReportLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_report_log
     *
     * @mbggenerated
     */
    UserReportLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_report_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserReportLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_report_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserReportLog record);
    
    List<String> selectCheckDate(long userId);
    
    void intsertReportLog(HashMap<String,Object> map);
 
    void deleteReportsLog();
    
}