package com.sky.game.service.persistence;

import java.util.HashMap;
import java.util.List;

import com.sky.game.service.domain.UserVip;

public interface UserVipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vip
     *
     * @mbggenerated
     */
    int insert(UserVip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vip
     *
     * @mbggenerated
     */
    int insertSelective(UserVip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vip
     *
     * @mbggenerated
     */
    UserVip selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vip
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserVip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vip
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserVip record);
    
    void updateGiftVip(HashMap<String,Object> hashmap);
    
    void insertGiftVip(HashMap<String,Object> hashmap);
    
    int selectVipLevel(long userId);
    /*
     * 根据用户id查询用户的vip记录
     */
    UserVip selectVipOn(long userId);
    
    void updateVipLevel(HashMap<String,Object> hashmap);

    void insertVipLevel(HashMap<String,Object> hashmap);
    
    List<UserVip> selectViP();
    
}