package com.sky.game.service.persistence;

import java.util.Date;
import java.util.HashMap;

import com.sky.game.service.domain.UserBank;

public interface UserBankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank
     *
     * @mbggenerated
     */
    int insert(UserBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank
     *
     * @mbggenerated
     */
    int insertSelective(UserBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank
     *
     * @mbggenerated
     */
    UserBank selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserBank record);
    
    
    
    void updateDeposit(HashMap<String,Object> map); 
    
    void selectUserId(long userId);
    
    void insertDeposit(HashMap<String,Object> map);
    
    void takeDeposit(HashMap<String,Object> map);
    /*
     * 根据UserId  查询银行密码
     */
    String selectBankPw(long userId);
    
    int selectUserLoan(long userId);
    
    int selectUserRepayment(long userId);
    
    void updateUserLoan(HashMap<String,Object> map);
    
    void insertUserLoan(HashMap<String,Object> map);
    
    Date selectLoanDate(long userId);
    
    void updateRepayment(HashMap<String,Object> map);
    
    void updateBackLoan(HashMap<String,Object> map);
    
    Date selectRefundDate(long userId);
    /*
     * 插入个人银行密码
     */
    int insertBankPw(HashMap<String,Object> hashmap);
    
    int selectUserdDeposit(long userId);
    
    int updateFreezeDeposit(HashMap<String,Object> hashmap);
	/*
	 * 根据用户id查询用户银行信息    
	 */
    UserBank selectUserBankByUserId(long userId);

    //UserBank selectUserBank(long userId);
    
    void updateUserLoanStart(HashMap<String,Object> map);
    
    void reset(long userId);
    
    void decReputationValue(HashMap<String,Object> map);
   
    
    
}