package com.sky.game.service.persistence;

import java.util.HashMap;
import java.util.List;

import com.sky.game.service.domain.PropertyShow;
import com.sky.game.service.domain.UserExtra;

public interface UserExtraMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extra
     *
     * @mbggenerated
     */
    int insert(UserExtra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extra
     *
     * @mbggenerated
     */
    int insertSelective(UserExtra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extra
     *
     * @mbggenerated
     */
    UserExtra selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extra
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserExtra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extra
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserExtra record);

    
    /*
     * 根据userId查询用户属性
     *   */
    List<PropertyShow> userPropertyList(Long userId);

    
    
    List<UserExtra> selectByAccountId(Long id);
    
    void updateNickName(HashMap<String,Object> map);
    
    void updateUserSign(HashMap<String,Object> map);
    
    void updateUserPhone(HashMap<String,Object> map);
    
    int selectLevelExp(int experience);
    
    int selectNextExp(int experience);
              
    /*
     * 密码找回。根据电话号码查询userExtra 
     */
    UserExtra selectUserExtraByPhone(String phone);
    /*
     * 保存头像
     */
   int updateUserStartHead(HashMap<String,Object> hashmap);
   /*
    * 找回密码   根据phone 找回帐号
    */
   String selectUserAccountByPhone(String phone);
   
   int updateAddUserExp(HashMap<String,Object> hashmap);

   /*
    * 根据用户id查询用户昵称，属性
    * 
    */
   UserExtra selectNickNameByUserId(long userId);

  
   List<UserExtra> selectUserExtra(HashMap<String,Object> map);
   
   int selectMaxExp();

   /*
    * 查询所有用户的手机号码
    */
   List<UserExtra> selectAllPhone();
   
   /*
    * 最大经验数   个人中心中的经验进度   GU0008
    */
 
   /*
    * 根据电话号码查询UserExtra
    */
   long byPhoneSelectUserExtra(String phone);
   
   UserExtra   selectByAccountIdAndPropertyId(Long userId,Long propertyId);
   
   void updateReputationValue(HashMap<String,Object> map);
   
   void updateUserExtraVip(long userId);
   /**
    * 查询用户是否是vip
    * @param userId
    * @return
    */
   UserExtra selectUserIsVip(long userId);
   
   void insertUserExtraVip(long userId);
   /**
    * 根据userId and property_id 查询userExtra
    * @param hashmap
    * @return
    */
   UserExtra selectByUserIdAndProperty(HashMap<String,Object> hashmap);
   
   UserExtra selectReputationValue(long userId);
   
   void updateUserVipType(long userId);
   /**
    * 删除youke 属性
    */
   int deleteUserPropertyId(long userAccountId);
   /**
    * 修改用户属性针对  大师分，天梯分，魅力值
    * @param hashmap
    * @return
    */
   int updateDTM(HashMap<String,Object> hashmap);
   /**
    * 添加  大师分，天梯分，魅力值
    */
   int insertDTM(HashMap<String,Object> hashmap);
}