package com.sky.game.service.persistence;

import com.sky.game.service.domain.UserPropertiesLog;

public interface UserPropertiesLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_properties_log
     *
     * @mbggenerated
     */
    int insert(UserPropertiesLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_properties_log
     *
     * @mbggenerated
     */
    int insertSelective(UserPropertiesLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_properties_log
     *
     * @mbggenerated
     */
    UserPropertiesLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_properties_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserPropertiesLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_properties_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserPropertiesLog record);
}