package com.sky.game.service.persistence;

import com.sky.game.service.domain.UserActivity;

public interface UserActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbggenerated
     */
    int insert(UserActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbggenerated
     */
    int insertSelective(UserActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbggenerated
     */
    UserActivity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserActivity record);
    
    UserActivity selectByUserId(long userId);
    
    void insertUserActivity(long userId);
}