package com.sky.game.service.domain;

public class ChannelItems {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_items.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_items.channel_id
     *
     * @mbggenerated
     */
    private Long channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_items.channel_item_id
     *
     * @mbggenerated
     */
    private Long channelItemId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_items.id
     *
     * @return the value of channel_items.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_items.id
     *
     * @param id the value for channel_items.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_items.channel_id
     *
     * @return the value of channel_items.channel_id
     *
     * @mbggenerated
     */
    public Long getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_items.channel_id
     *
     * @param channelId the value for channel_items.channel_id
     *
     * @mbggenerated
     */
    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_items.channel_item_id
     *
     * @return the value of channel_items.channel_item_id
     *
     * @mbggenerated
     */
    public Long getChannelItemId() {
        return channelItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_items.channel_item_id
     *
     * @param channelItemId the value for channel_items.channel_item_id
     *
     * @mbggenerated
     */
    public void setChannelItemId(Long channelItemId) {
        this.channelItemId = channelItemId;
    }
}