package com.sky.game.service.domain;

import java.util.Date;

public class Flag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flag.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flag.itme_id
     *
     * @mbggenerated
     */
    private Long itmeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flag.flag_id
     *
     * @mbggenerated
     */
    private Long flagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flag.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flag.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flag.id
     *
     * @return the value of flag.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flag.id
     *
     * @param id the value for flag.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flag.itme_id
     *
     * @return the value of flag.itme_id
     *
     * @mbggenerated
     */
    public Long getItmeId() {
        return itmeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flag.itme_id
     *
     * @param itmeId the value for flag.itme_id
     *
     * @mbggenerated
     */
    public void setItmeId(Long itmeId) {
        this.itmeId = itmeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flag.flag_id
     *
     * @return the value of flag.flag_id
     *
     * @mbggenerated
     */
    public Long getFlagId() {
        return flagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flag.flag_id
     *
     * @param flagId the value for flag.flag_id
     *
     * @mbggenerated
     */
    public void setFlagId(Long flagId) {
        this.flagId = flagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flag.time
     *
     * @return the value of flag.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flag.time
     *
     * @param time the value for flag.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flag.user_id
     *
     * @return the value of flag.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flag.user_id
     *
     * @param userId the value for flag.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}