package com.sky.game.service.domain;

public class Freeze {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freeze.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freeze.point_card_id
     *
     * @mbggenerated
     */
    private Long pointCardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freeze.owner_id
     *
     * @mbggenerated
     */
    private Long ownerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freeze.user_account_id
     *
     * @mbggenerated
     */
    private Long userAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freeze.freeze_count
     *
     * @mbggenerated
     */
    private Integer freezeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freeze.freeze_item_id
     *
     * @mbggenerated
     */
    private Long freezeItemId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freeze.id
     *
     * @return the value of freeze.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freeze.id
     *
     * @param id the value for freeze.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freeze.point_card_id
     *
     * @return the value of freeze.point_card_id
     *
     * @mbggenerated
     */
    public Long getPointCardId() {
        return pointCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freeze.point_card_id
     *
     * @param pointCardId the value for freeze.point_card_id
     *
     * @mbggenerated
     */
    public void setPointCardId(Long pointCardId) {
        this.pointCardId = pointCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freeze.owner_id
     *
     * @return the value of freeze.owner_id
     *
     * @mbggenerated
     */
    public Long getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freeze.owner_id
     *
     * @param ownerId the value for freeze.owner_id
     *
     * @mbggenerated
     */
    public void setOwnerId(Long ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freeze.user_account_id
     *
     * @return the value of freeze.user_account_id
     *
     * @mbggenerated
     */
    public Long getUserAccountId() {
        return userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freeze.user_account_id
     *
     * @param userAccountId the value for freeze.user_account_id
     *
     * @mbggenerated
     */
    public void setUserAccountId(Long userAccountId) {
        this.userAccountId = userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freeze.freeze_count
     *
     * @return the value of freeze.freeze_count
     *
     * @mbggenerated
     */
    public Integer getFreezeCount() {
        return freezeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freeze.freeze_count
     *
     * @param freezeCount the value for freeze.freeze_count
     *
     * @mbggenerated
     */
    public void setFreezeCount(Integer freezeCount) {
        this.freezeCount = freezeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freeze.freeze_item_id
     *
     * @return the value of freeze.freeze_item_id
     *
     * @mbggenerated
     */
    public Long getFreezeItemId() {
        return freezeItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freeze.freeze_item_id
     *
     * @param freezeItemId the value for freeze.freeze_item_id
     *
     * @mbggenerated
     */
    public void setFreezeItemId(Long freezeItemId) {
        this.freezeItemId = freezeItemId;
    }
}