package com.sky.game.service.domain;

import java.util.Date;

public class GameBlockadeLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_blockade_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_blockade_log.game_blockade_user_id
     *
     * @mbggenerated
     */
    private Long gameBlockadeUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_blockade_log.old_value
     *
     * @mbggenerated
     */
    private Long oldValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_blockade_log.value
     *
     * @mbggenerated
     */
    private Long value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_blockade_log.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_blockade_log.id
     *
     * @return the value of game_blockade_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_blockade_log.id
     *
     * @param id the value for game_blockade_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_blockade_log.game_blockade_user_id
     *
     * @return the value of game_blockade_log.game_blockade_user_id
     *
     * @mbggenerated
     */
    public Long getGameBlockadeUserId() {
        return gameBlockadeUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_blockade_log.game_blockade_user_id
     *
     * @param gameBlockadeUserId the value for game_blockade_log.game_blockade_user_id
     *
     * @mbggenerated
     */
    public void setGameBlockadeUserId(Long gameBlockadeUserId) {
        this.gameBlockadeUserId = gameBlockadeUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_blockade_log.old_value
     *
     * @return the value of game_blockade_log.old_value
     *
     * @mbggenerated
     */
    public Long getOldValue() {
        return oldValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_blockade_log.old_value
     *
     * @param oldValue the value for game_blockade_log.old_value
     *
     * @mbggenerated
     */
    public void setOldValue(Long oldValue) {
        this.oldValue = oldValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_blockade_log.value
     *
     * @return the value of game_blockade_log.value
     *
     * @mbggenerated
     */
    public Long getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_blockade_log.value
     *
     * @param value the value for game_blockade_log.value
     *
     * @mbggenerated
     */
    public void setValue(Long value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_blockade_log.create_time
     *
     * @return the value of game_blockade_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_blockade_log.create_time
     *
     * @param createTime the value for game_blockade_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}