package com.sky.game.service.domain;

import java.util.Date;

public class GameBlockadeUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_blockade_user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_blockade_user.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_blockade_user.room_id
     *
     * @mbggenerated
     */
    private Long roomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_blockade_user.integral
     *
     * @mbggenerated
     */
    private Long integral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_blockade_user.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_blockade_user.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_blockade_user.id
     *
     * @return the value of game_blockade_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_blockade_user.id
     *
     * @param id the value for game_blockade_user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_blockade_user.user_id
     *
     * @return the value of game_blockade_user.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_blockade_user.user_id
     *
     * @param userId the value for game_blockade_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_blockade_user.room_id
     *
     * @return the value of game_blockade_user.room_id
     *
     * @mbggenerated
     */
    public Long getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_blockade_user.room_id
     *
     * @param roomId the value for game_blockade_user.room_id
     *
     * @mbggenerated
     */
    public void setRoomId(Long roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_blockade_user.integral
     *
     * @return the value of game_blockade_user.integral
     *
     * @mbggenerated
     */
    public Long getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_blockade_user.integral
     *
     * @param integral the value for game_blockade_user.integral
     *
     * @mbggenerated
     */
    public void setIntegral(Long integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_blockade_user.level
     *
     * @return the value of game_blockade_user.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_blockade_user.level
     *
     * @param level the value for game_blockade_user.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_blockade_user.update_time
     *
     * @return the value of game_blockade_user.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_blockade_user.update_time
     *
     * @param updateTime the value for game_blockade_user.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    
   
    
    
}