package com.sky.game.service.domain;

import java.util.Date;

public class GameEnroll {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_enroll.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_enroll.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_enroll.room_id
     *
     * @mbggenerated
     */
    private Long roomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_enroll.user_item_log_id
     *
     * @mbggenerated
     */
    private Long userItemLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_enroll.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_enroll.team_id
     *
     * @mbggenerated
     */
    private Long teamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_enroll.enrolled
     *
     * @mbggenerated
     */
    private Integer enrolled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_enroll.id
     *
     * @return the value of game_enroll.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_enroll.id
     *
     * @param id the value for game_enroll.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_enroll.user_id
     *
     * @return the value of game_enroll.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_enroll.user_id
     *
     * @param userId the value for game_enroll.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_enroll.room_id
     *
     * @return the value of game_enroll.room_id
     *
     * @mbggenerated
     */
    public Long getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_enroll.room_id
     *
     * @param roomId the value for game_enroll.room_id
     *
     * @mbggenerated
     */
    public void setRoomId(Long roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_enroll.user_item_log_id
     *
     * @return the value of game_enroll.user_item_log_id
     *
     * @mbggenerated
     */
    public Long getUserItemLogId() {
        return userItemLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_enroll.user_item_log_id
     *
     * @param userItemLogId the value for game_enroll.user_item_log_id
     *
     * @mbggenerated
     */
    public void setUserItemLogId(Long userItemLogId) {
        this.userItemLogId = userItemLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_enroll.create_time
     *
     * @return the value of game_enroll.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_enroll.create_time
     *
     * @param createTime the value for game_enroll.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_enroll.team_id
     *
     * @return the value of game_enroll.team_id
     *
     * @mbggenerated
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_enroll.team_id
     *
     * @param teamId the value for game_enroll.team_id
     *
     * @mbggenerated
     */
    public void setTeamId(Long teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_enroll.enrolled
     *
     * @return the value of game_enroll.enrolled
     *
     * @mbggenerated
     */
    public Integer getEnrolled() {
        return enrolled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_enroll.enrolled
     *
     * @param enrolled the value for game_enroll.enrolled
     *
     * @mbggenerated
     */
    public void setEnrolled(Integer enrolled) {
        this.enrolled = enrolled;
    }
}