package com.sky.game.service.domain;

import java.io.Serializable;

public class Icon implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column icon.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column icon.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column icon.descript
     *
     * @mbggenerated
     */
    private String descript;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column icon.id
     *
     * @return the value of icon.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column icon.id
     *
     * @param id the value for icon.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column icon.url
     *
     * @return the value of icon.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column icon.url
     *
     * @param url the value for icon.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column icon.descript
     *
     * @return the value of icon.descript
     *
     * @mbggenerated
     */
    public String getDescript() {
        return descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column icon.descript
     *
     * @param descript the value for icon.descript
     *
     * @mbggenerated
     */
    public void setDescript(String descript) {
        this.descript = descript == null ? null : descript.trim();
    }
}