package com.sky.game.service.domain;

import java.util.Date;

public class PoinCard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card.type_id
     *
     * @mbggenerated
     */
    private Long typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card.start_price
     *
     * @mbggenerated
     */
    private Integer startPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card.now_price
     *
     * @mbggenerated
     */
    private Integer nowPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card.user_account_id
     *
     * @mbggenerated
     */
    private Long userAccountId;
    
    private Long iconId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card.name
     *
     * @mbggenerated
     */
    private String name;

   

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card.own_fen
     *
     * @mbggenerated
     */
    private Integer ownFen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card.get_time
     *
     * @mbggenerated
     */
    private Date getTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card.start_time
     *
     * @mbggenerated
     */
    private Date startTime;
    private Long roomId;
    
    public Long getRoomId() {
		return roomId;
	}

	public void setRoomId(Long roomId) {
		this.roomId = roomId;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card.effect_time
     *
     * @mbggenerated
     */
    private Date effectTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card.last_tarde_price
     *
     * @mbggenerated
     */
    private Integer lastTardePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card.trade_type
     *
     * @mbggenerated
     */
    private String tradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card.out_type
     *
     * @mbggenerated
     */
    private String outType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card.id
     *
     * @return the value of point_card.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card.id
     *
     * @param id the value for point_card.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card.type_id
     *
     * @return the value of point_card.type_id
     *
     * @mbggenerated
     */
    public Long getTypeId() {
        return typeId;
    }

    public Long getIconId() {
		return iconId;
	}

	public void setIconId(Long iconId) {
		this.iconId = iconId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card.type_id
     *
     * @param typeId the value for point_card.type_id
     *
     * @mbggenerated
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card.start_price
     *
     * @return the value of point_card.start_price
     *
     * @mbggenerated
     */
    public Integer getStartPrice() {
        return startPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card.start_price
     *
     * @param startPrice the value for point_card.start_price
     *
     * @mbggenerated
     */
    public void setStartPrice(Integer startPrice) {
        this.startPrice = startPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card.now_price
     *
     * @return the value of point_card.now_price
     *
     * @mbggenerated
     */
    public Integer getNowPrice() {
        return nowPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card.now_price
     *
     * @param nowPrice the value for point_card.now_price
     *
     * @mbggenerated
     */
    public void setNowPrice(Integer nowPrice) {
        this.nowPrice = nowPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card.user_account_id
     *
     * @return the value of point_card.user_account_id
     *
     * @mbggenerated
     */
    public Long getUserAccountId() {
        return userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card.user_account_id
     *
     * @param userAccountId the value for point_card.user_account_id
     *
     * @mbggenerated
     */
    public void setUserAccountId(Long userAccountId) {
        this.userAccountId = userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card.name
     *
     * @return the value of point_card.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card.name
     *
     * @param name the value for point_card.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

   

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card.match
     *
     * @param match the value for point_card.match
     *
     * @mbggenerated
     */
   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card.own_fen
     *
     * @return the value of point_card.own_fen
     *
     * @mbggenerated
     */
    public Integer getOwnFen() {
        return ownFen;
    }

  
	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card.own_fen
     *
     * @param ownFen the value for point_card.own_fen
     *
     * @mbggenerated
     */
    public void setOwnFen(Integer ownFen) {
        this.ownFen = ownFen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card.get_time
     *
     * @return the value of point_card.get_time
     *
     * @mbggenerated
     */
    public Date getGetTime() {
        return getTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card.get_time
     *
     * @param getTime the value for point_card.get_time
     *
     * @mbggenerated
     */
    public void setGetTime(Date getTime) {
        this.getTime = getTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card.start_time
     *
     * @return the value of point_card.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card.start_time
     *
     * @param startTime the value for point_card.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card.end_time
     *
     * @return the value of point_card.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card.end_time
     *
     * @param endTime the value for point_card.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card.effect_time
     *
     * @return the value of point_card.effect_time
     *
     * @mbggenerated
     */
    public Date getEffectTime() {
        return effectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card.effect_time
     *
     * @param effectTime the value for point_card.effect_time
     *
     * @mbggenerated
     */
    public void setEffectTime(Date effectTime) {
        this.effectTime = effectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card.count
     *
     * @return the value of point_card.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card.count
     *
     * @param count the value for point_card.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card.last_tarde_price
     *
     * @return the value of point_card.last_tarde_price
     *
     * @mbggenerated
     */
    public Integer getLastTardePrice() {
        return lastTardePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card.last_tarde_price
     *
     * @param lastTardePrice the value for point_card.last_tarde_price
     *
     * @mbggenerated
     */
    public void setLastTardePrice(Integer lastTardePrice) {
        this.lastTardePrice = lastTardePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card.flag
     *
     * @return the value of point_card.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card.flag
     *
     * @param flag the value for point_card.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card.trade_type
     *
     * @return the value of point_card.trade_type
     *
     * @mbggenerated
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card.trade_type
     *
     * @param tradeType the value for point_card.trade_type
     *
     * @mbggenerated
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card.out_type
     *
     * @return the value of point_card.out_type
     *
     * @mbggenerated
     */
    public String getOutType() {
        return outType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card.out_type
     *
     * @param outType the value for point_card.out_type
     *
     * @mbggenerated
     */
    public void setOutType(String outType) {
        this.outType = outType == null ? null : outType.trim();
    }
}