package com.sky.game.service.domain;

import java.util.Date;

public class PoinCardAttribute {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card_attribute.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card_attribute.type_name
     *
     * @mbggenerated
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card_attribute.use_area
     *
     * @mbggenerated
     */
    private String useArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card_attribute.effect_time
     *
     * @mbggenerated
     */
    private Date effectTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card_attribute.auction_time
     *
     * @mbggenerated
     */
    private Date auctionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card_attribute.trade_type
     *
     * @mbggenerated
     */
    private String tradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card_attribute.low_out_price
     *
     * @mbggenerated
     */
    private Integer lowOutPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card_attribute.hight_out_price
     *
     * @mbggenerated
     */
    private Integer hightOutPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card_attribute.allow_out_type
     *
     * @mbggenerated
     */
    private String allowOutType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card_attribute.small_add_price
     *
     * @mbggenerated
     */
    private Integer smallAddPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card_attribute.allow_out_count
     *
     * @mbggenerated
     */
    private Integer allowOutCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card_attribute.charges
     *
     * @mbggenerated
     */
    private Integer charges;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_card_attribute.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card_attribute.id
     *
     * @return the value of point_card_attribute.id
     *
     * @mbggenerated
     */
    
    private Date loseEffectTime;
    
    public Date getLoseEffectTime() {
		return loseEffectTime;
	}

	public void setLoseEffectTime(Date loseEffectTime) {
		this.loseEffectTime = loseEffectTime;
	}

	public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card_attribute.id
     *
     * @param id the value for point_card_attribute.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card_attribute.type_name
     *
     * @return the value of point_card_attribute.type_name
     *
     * @mbggenerated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card_attribute.type_name
     *
     * @param typeName the value for point_card_attribute.type_name
     *
     * @mbggenerated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card_attribute.use_area
     *
     * @return the value of point_card_attribute.use_area
     *
     * @mbggenerated
     */
    public String getUseArea() {
        return useArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card_attribute.use_area
     *
     * @param useArea the value for point_card_attribute.use_area
     *
     * @mbggenerated
     */
    public void setUseArea(String useArea) {
        this.useArea = useArea == null ? null : useArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card_attribute.effect_time
     *
     * @return the value of point_card_attribute.effect_time
     *
     * @mbggenerated
     */
    public Date getEffectTime() {
        return effectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card_attribute.effect_time
     *
     * @param effectTime the value for point_card_attribute.effect_time
     *
     * @mbggenerated
     */
    public void setEffectTime(Date effectTime) {
        this.effectTime = effectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card_attribute.auction_time
     *
     * @return the value of point_card_attribute.auction_time
     *
     * @mbggenerated
     */
    public Date getAuctionTime() {
        return auctionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card_attribute.auction_time
     *
     * @param auctionTime the value for point_card_attribute.auction_time
     *
     * @mbggenerated
     */
    public void setAuctionTime(Date auctionTime) {
        this.auctionTime = auctionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card_attribute.trade_type
     *
     * @return the value of point_card_attribute.trade_type
     *
     * @mbggenerated
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card_attribute.trade_type
     *
     * @param tradeType the value for point_card_attribute.trade_type
     *
     * @mbggenerated
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card_attribute.low_out_price
     *
     * @return the value of point_card_attribute.low_out_price
     *
     * @mbggenerated
     */
    public Integer getLowOutPrice() {
        return lowOutPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card_attribute.low_out_price
     *
     * @param lowOutPrice the value for point_card_attribute.low_out_price
     *
     * @mbggenerated
     */
    public void setLowOutPrice(Integer lowOutPrice) {
        this.lowOutPrice = lowOutPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card_attribute.hight_out_price
     *
     * @return the value of point_card_attribute.hight_out_price
     *
     * @mbggenerated
     */
    public Integer getHightOutPrice() {
        return hightOutPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card_attribute.hight_out_price
     *
     * @param hightOutPrice the value for point_card_attribute.hight_out_price
     *
     * @mbggenerated
     */
    public void setHightOutPrice(Integer hightOutPrice) {
        this.hightOutPrice = hightOutPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card_attribute.allow_out_type
     *
     * @return the value of point_card_attribute.allow_out_type
     *
     * @mbggenerated
     */
    public String getAllowOutType() {
        return allowOutType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card_attribute.allow_out_type
     *
     * @param allowOutType the value for point_card_attribute.allow_out_type
     *
     * @mbggenerated
     */
    public void setAllowOutType(String allowOutType) {
        this.allowOutType = allowOutType == null ? null : allowOutType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card_attribute.small_add_price
     *
     * @return the value of point_card_attribute.small_add_price
     *
     * @mbggenerated
     */
    public Integer getSmallAddPrice() {
        return smallAddPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card_attribute.small_add_price
     *
     * @param smallAddPrice the value for point_card_attribute.small_add_price
     *
     * @mbggenerated
     */
    public void setSmallAddPrice(Integer smallAddPrice) {
        this.smallAddPrice = smallAddPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card_attribute.allow_out_count
     *
     * @return the value of point_card_attribute.allow_out_count
     *
     * @mbggenerated
     */
    public Integer getAllowOutCount() {
        return allowOutCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card_attribute.allow_out_count
     *
     * @param allowOutCount the value for point_card_attribute.allow_out_count
     *
     * @mbggenerated
     */
    public void setAllowOutCount(Integer allowOutCount) {
        this.allowOutCount = allowOutCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card_attribute.charges
     *
     * @return the value of point_card_attribute.charges
     *
     * @mbggenerated
     */
    public Integer getCharges() {
        return charges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card_attribute.charges
     *
     * @param charges the value for point_card_attribute.charges
     *
     * @mbggenerated
     */
    public void setCharges(Integer charges) {
        this.charges = charges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_card_attribute.description
     *
     * @return the value of point_card_attribute.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_card_attribute.description
     *
     * @param description the value for point_card_attribute.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}