package com.sky.game.service.domain;

public class PrivilegeDetailed {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege_detailed.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege_detailed.vip_level
     *
     * @mbggenerated
     */
    private Integer vipLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege_detailed.goods_discount
     *
     * @mbggenerated
     */
    private Integer goodsDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege_detailed.lottery_count
     *
     * @mbggenerated
     */
    private Integer lotteryCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege_detailed.add_message
     *
     * @mbggenerated
     */
    private Integer addMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege_detailed.add_exp
     *
     * @mbggenerated
     */
    private Float addExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege_detailed.frends_max
     *
     * @mbggenerated
     */
    private Integer frendsMax;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege_detailed.id
     *
     * @return the value of privilege_detailed.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege_detailed.id
     *
     * @param id the value for privilege_detailed.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege_detailed.vip_level
     *
     * @return the value of privilege_detailed.vip_level
     *
     * @mbggenerated
     */
    public Integer getVipLevel() {
        return vipLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege_detailed.vip_level
     *
     * @param vipLevel the value for privilege_detailed.vip_level
     *
     * @mbggenerated
     */
    public void setVipLevel(Integer vipLevel) {
        this.vipLevel = vipLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege_detailed.goods_discount
     *
     * @return the value of privilege_detailed.goods_discount
     *
     * @mbggenerated
     */
    public Integer getGoodsDiscount() {
        return goodsDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege_detailed.goods_discount
     *
     * @param goodsDiscount the value for privilege_detailed.goods_discount
     *
     * @mbggenerated
     */
    public void setGoodsDiscount(Integer goodsDiscount) {
        this.goodsDiscount = goodsDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege_detailed.lottery_count
     *
     * @return the value of privilege_detailed.lottery_count
     *
     * @mbggenerated
     */
    public Integer getLotteryCount() {
        return lotteryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege_detailed.lottery_count
     *
     * @param lotteryCount the value for privilege_detailed.lottery_count
     *
     * @mbggenerated
     */
    public void setLotteryCount(Integer lotteryCount) {
        this.lotteryCount = lotteryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege_detailed.add_message
     *
     * @return the value of privilege_detailed.add_message
     *
     * @mbggenerated
     */
    public Integer getAddMessage() {
        return addMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege_detailed.add_message
     *
     * @param addMessage the value for privilege_detailed.add_message
     *
     * @mbggenerated
     */
    public void setAddMessage(Integer addMessage) {
        this.addMessage = addMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege_detailed.add_exp
     *
     * @return the value of privilege_detailed.add_exp
     *
     * @mbggenerated
     */
    public Float getAddExp() {
        return addExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege_detailed.add_exp
     *
     * @param addExp the value for privilege_detailed.add_exp
     *
     * @mbggenerated
     */
    public void setAddExp(Float addExp) {
        this.addExp = addExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege_detailed.frends_max
     *
     * @return the value of privilege_detailed.frends_max
     *
     * @mbggenerated
     */
    public Integer getFrendsMax() {
        return frendsMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege_detailed.frends_max
     *
     * @param frendsMax the value for privilege_detailed.frends_max
     *
     * @mbggenerated
     */
    public void setFrendsMax(Integer frendsMax) {
        this.frendsMax = frendsMax;
    }
}