package com.sky.game.service.domain;

public class SystemChargeItems {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_charge_items.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_charge_items.charge_card_id
     *
     * @mbggenerated
     */
    private Long chargeCardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_charge_items.item_id
     *
     * @mbggenerated
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_charge_items.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_charge_items.id
     *
     * @return the value of system_charge_items.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_charge_items.id
     *
     * @param id the value for system_charge_items.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_charge_items.charge_card_id
     *
     * @return the value of system_charge_items.charge_card_id
     *
     * @mbggenerated
     */
    public Long getChargeCardId() {
        return chargeCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_charge_items.charge_card_id
     *
     * @param chargeCardId the value for system_charge_items.charge_card_id
     *
     * @mbggenerated
     */
    public void setChargeCardId(Long chargeCardId) {
        this.chargeCardId = chargeCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_charge_items.item_id
     *
     * @return the value of system_charge_items.item_id
     *
     * @mbggenerated
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_charge_items.item_id
     *
     * @param itemId the value for system_charge_items.item_id
     *
     * @mbggenerated
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_charge_items.count
     *
     * @return the value of system_charge_items.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_charge_items.count
     *
     * @param count the value for system_charge_items.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}