package com.sky.game.service.domain;

public class UserReportLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_report_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_report_log.user_account_id
     *
     * @mbggenerated
     */
    private Long userAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_report_log.check_date
     *
     * @mbggenerated
     */
    private String checkDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_report_log.check_gold
     *
     * @mbggenerated
     */
    private Integer checkGold;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_report_log.id
     *
     * @return the value of user_report_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_report_log.id
     *
     * @param id the value for user_report_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_report_log.user_account_id
     *
     * @return the value of user_report_log.user_account_id
     *
     * @mbggenerated
     */
    public Long getUserAccountId() {
        return userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_report_log.user_account_id
     *
     * @param userAccountId the value for user_report_log.user_account_id
     *
     * @mbggenerated
     */
    public void setUserAccountId(Long userAccountId) {
        this.userAccountId = userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_report_log.check_date
     *
     * @return the value of user_report_log.check_date
     *
     * @mbggenerated
     */
    public String getCheckDate() {
        return checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_report_log.check_date
     *
     * @param checkDate the value for user_report_log.check_date
     *
     * @mbggenerated
     */
    public void setCheckDate(String checkDate) {
        this.checkDate = checkDate == null ? null : checkDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_report_log.check_gold
     *
     * @return the value of user_report_log.check_gold
     *
     * @mbggenerated
     */
    public Integer getCheckGold() {
        return checkGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_report_log.check_gold
     *
     * @param checkGold the value for user_report_log.check_gold
     *
     * @mbggenerated
     */
    public void setCheckGold(Integer checkGold) {
        this.checkGold = checkGold;
    }
}