package com.sky.game.service.domain;

import java.io.Serializable;

public class UserLevel  implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_level.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_level.exp
     *
     * @mbggenerated
     */
    private Long exp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_level.level_name
     *
     * @mbggenerated
     */
    private String levelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_level.level_value
     *
     * @mbggenerated
     */
    private Integer levelValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_level.id
     *
     * @return the value of user_level.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_level.id
     *
     * @param id the value for user_level.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_level.exp
     *
     * @return the value of user_level.exp
     *
     * @mbggenerated
     */
    public Long getExp() {
        return exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_level.exp
     *
     * @param exp the value for user_level.exp
     *
     * @mbggenerated
     */
    public void setExp(Long exp) {
        this.exp = exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_level.level_name
     *
     * @return the value of user_level.level_name
     *
     * @mbggenerated
     */
    public String getLevelName() {
        return levelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_level.level_name
     *
     * @param levelName the value for user_level.level_name
     *
     * @mbggenerated
     */
    public void setLevelName(String levelName) {
        this.levelName = levelName == null ? null : levelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_level.level_value
     *
     * @return the value of user_level.level_value
     *
     * @mbggenerated
     */
    public Integer getLevelValue() {
        return levelValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_level.level_value
     *
     * @param levelValue the value for user_level.level_value
     *
     * @mbggenerated
     */
    public void setLevelValue(Integer levelValue) {
        this.levelValue = levelValue;
    }
}