package com.sky.game.service.domain;

public class UserMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_message.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_message.user_account_id
     *
     * @mbggenerated
     */
    private Long userAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_message.sys_message_id
     *
     * @mbggenerated
     */
    private Long sysMessageId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_message.id
     *
     * @return the value of user_message.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_message.id
     *
     * @param id the value for user_message.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_message.user_account_id
     *
     * @return the value of user_message.user_account_id
     *
     * @mbggenerated
     */
    public Long getUserAccountId() {
        return userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_message.user_account_id
     *
     * @param userAccountId the value for user_message.user_account_id
     *
     * @mbggenerated
     */
    public void setUserAccountId(Long userAccountId) {
        this.userAccountId = userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_message.sys_message_id
     *
     * @return the value of user_message.sys_message_id
     *
     * @mbggenerated
     */
    public Long getSysMessageId() {
        return sysMessageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_message.sys_message_id
     *
     * @param sysMessageId the value for user_message.sys_message_id
     *
     * @mbggenerated
     */
    public void setSysMessageId(Long sysMessageId) {
        this.sysMessageId = sysMessageId;
    }
}