package com.sky.game.service.domain;

public class UserActivity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_activity.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_activity.user_account_id
     *
     * @mbggenerated
     */
    private Long userAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_activity.activity_id
     *
     * @mbggenerated
     */
    private Long activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_activity.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_activity.id
     *
     * @return the value of user_activity.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_activity.id
     *
     * @param id the value for user_activity.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_activity.user_account_id
     *
     * @return the value of user_activity.user_account_id
     *
     * @mbggenerated
     */
    public Long getUserAccountId() {
        return userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_activity.user_account_id
     *
     * @param userAccountId the value for user_activity.user_account_id
     *
     * @mbggenerated
     */
    public void setUserAccountId(Long userAccountId) {
        this.userAccountId = userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_activity.activity_id
     *
     * @return the value of user_activity.activity_id
     *
     * @mbggenerated
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_activity.activity_id
     *
     * @param activityId the value for user_activity.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_activity.state
     *
     * @return the value of user_activity.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_activity.state
     *
     * @param state the value for user_activity.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}