package com.sky.game.service.domain;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnore;

public class UserToken {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_token.id
	 *
	 * @mbggenerated
	 */
	@JsonIgnore
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_token.user_id
	 *
	 * @mbggenerated
	 */
	private Long userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_token.update_time
	 *
	 * @mbggenerated
	 */
	
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_token.login_times
	 *
	 * @mbggenerated
	 */
	@JsonIgnore
	private Integer loginTimes;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_token.last_update_time
	 *
	 * @mbggenerated
	 */
	@JsonIgnore
	private Date lastUpdateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_token.token
	 *
	 * @mbggenerated
	 */
	@JsonIgnore
	private String token;

	/**
	 * this field is not part of the table.
	 * 
	 */
	
	private long tokenAliveTime;

	public long getTokenAliveTime() {
		return tokenAliveTime;
	}

	public void setTokenAliveTime(long tokenAliveTime) {
		this.tokenAliveTime = tokenAliveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_token.id
	 *
	 * @return the value of user_token.id
	 *
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_token.id
	 *
	 * @param id
	 *            the value for user_token.id
	 *
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_token.user_id
	 *
	 * @return the value of user_token.user_id
	 *
	 * @mbggenerated
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_token.user_id
	 *
	 * @param userId
	 *            the value for user_token.user_id
	 *
	 * @mbggenerated
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_token.update_time
	 *
	 * @return the value of user_token.update_time
	 *
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_token.update_time
	 *
	 * @param updateTime
	 *            the value for user_token.update_time
	 *
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_token.login_times
	 *
	 * @return the value of user_token.login_times
	 *
	 * @mbggenerated
	 */
	public Integer getLoginTimes() {
		return loginTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_token.login_times
	 *
	 * @param loginTimes
	 *            the value for user_token.login_times
	 *
	 * @mbggenerated
	 */
	public void setLoginTimes(Integer loginTimes) {
		this.loginTimes = loginTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_token.last_update_time
	 *
	 * @return the value of user_token.last_update_time
	 *
	 * @mbggenerated
	 */
	public Date getLastUpdateTime() {
		return lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_token.last_update_time
	 *
	 * @param lastUpdateTime
	 *            the value for user_token.last_update_time
	 *
	 * @mbggenerated
	 */
	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_token.token
	 *
	 * @return the value of user_token.token
	 *
	 * @mbggenerated
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_token.token
	 *
	 * @param token
	 *            the value for user_token.token
	 *
	 * @mbggenerated
	 */
	public void setToken(String token) {
		this.token = token == null ? null : token.trim();
	}

	public UserToken() {
		super();
		// TODO Auto-generated constructor stub
	}

	public UserToken(Long id, Long userId, Date updateTime, Integer loginTimes,
			Date lastUpdateTime, String token, long tokenAliveTime) {
		super();
		this.id = id;
		this.userId = userId;
		this.updateTime = updateTime;
		this.loginTimes = loginTimes;
		this.lastUpdateTime = lastUpdateTime;
		this.token = token;
		this.tokenAliveTime = tokenAliveTime;
	}

}