package com.sky.game.service.domain;

import java.util.Date;

public class UserTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_task.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_task.user_account_id
     *
     * @mbggenerated
     */
    private Long userAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_task.achievement_id
     *
     * @mbggenerated
     */
    private Long achievementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_task.effect_time
     *
     * @mbggenerated
     */
    private Date effectTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_task.expire_time
     *
     * @mbggenerated
     */
    private Date expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_task.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_task.task_id
     *
     * @mbggenerated
     */
    private Long taskId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_task.id
     *
     * @return the value of user_task.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_task.id
     *
     * @param id the value for user_task.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_task.user_account_id
     *
     * @return the value of user_task.user_account_id
     *
     * @mbggenerated
     */
    public Long getUserAccountId() {
        return userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_task.user_account_id
     *
     * @param userAccountId the value for user_task.user_account_id
     *
     * @mbggenerated
     */
    public void setUserAccountId(Long userAccountId) {
        this.userAccountId = userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_task.achievement_id
     *
     * @return the value of user_task.achievement_id
     *
     * @mbggenerated
     */
    public Long getAchievementId() {
        return achievementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_task.achievement_id
     *
     * @param achievementId the value for user_task.achievement_id
     *
     * @mbggenerated
     */
    public void setAchievementId(Long achievementId) {
        this.achievementId = achievementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_task.effect_time
     *
     * @return the value of user_task.effect_time
     *
     * @mbggenerated
     */
    public Date getEffectTime() {
        return effectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_task.effect_time
     *
     * @param effectTime the value for user_task.effect_time
     *
     * @mbggenerated
     */
    public void setEffectTime(Date effectTime) {
        this.effectTime = effectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_task.expire_time
     *
     * @return the value of user_task.expire_time
     *
     * @mbggenerated
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_task.expire_time
     *
     * @param expireTime the value for user_task.expire_time
     *
     * @mbggenerated
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_task.state
     *
     * @return the value of user_task.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_task.state
     *
     * @param state the value for user_task.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_task.task_id
     *
     * @return the value of user_task.task_id
     *
     * @mbggenerated
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_task.task_id
     *
     * @param taskId the value for user_task.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }
}