package com.sky.game.service.domain;

public class UserAchievement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_achievement.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_achievement.user_account_id
     *
     * @mbggenerated
     */
    private Long userAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_achievement.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_achievement.value
     *
     * @mbggenerated
     */
    private Integer value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_achievement.system_achievement_id
     *
     * @mbggenerated
     */
    private Long systemAchievementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_achievement.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_achievement.id
     *
     * @return the value of user_achievement.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_achievement.id
     *
     * @param id the value for user_achievement.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_achievement.user_account_id
     *
     * @return the value of user_achievement.user_account_id
     *
     * @mbggenerated
     */
    public Long getUserAccountId() {
        return userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_achievement.user_account_id
     *
     * @param userAccountId the value for user_achievement.user_account_id
     *
     * @mbggenerated
     */
    public void setUserAccountId(Long userAccountId) {
        this.userAccountId = userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_achievement.state
     *
     * @return the value of user_achievement.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_achievement.state
     *
     * @param state the value for user_achievement.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_achievement.value
     *
     * @return the value of user_achievement.value
     *
     * @mbggenerated
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_achievement.value
     *
     * @param value the value for user_achievement.value
     *
     * @mbggenerated
     */
    public void setValue(Integer value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_achievement.system_achievement_id
     *
     * @return the value of user_achievement.system_achievement_id
     *
     * @mbggenerated
     */
    public Long getSystemAchievementId() {
        return systemAchievementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_achievement.system_achievement_id
     *
     * @param systemAchievementId the value for user_achievement.system_achievement_id
     *
     * @mbggenerated
     */
    public void setSystemAchievementId(Long systemAchievementId) {
        this.systemAchievementId = systemAchievementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_achievement.type
     *
     * @return the value of user_achievement.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_achievement.type
     *
     * @param type the value for user_achievement.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }
}