package com.sky.game.service.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.Map;

import com.sky.game.context.util.GameUtil;

public class UserAccount implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 6614257361768485787L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_account.id
	 *
	 * @mbggenerated
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_account.name
	 *
	 * @mbggenerated
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_account.nick_name
	 *
	 * @mbggenerated
	 */
	private String nickName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_account.user_password
	 *
	 * @mbggenerated
	 */
	private String userPassword;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_account.update_time
	 *
	 * @mbggenerated
	 */
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_account.create_time
	 *
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_account.user_type
	 *
	 * @mbggenerated
	 */
	private Integer userType;
	
	

	private List<UserExtra> properties;
	// need to know
	private List<UserItems> items;

	public List<UserExtra> getProperties() {
		return properties;
	}

	public void setProperties(List<UserExtra> properties) {
		this.properties = properties;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_account.id
	 *
	 * @return the value of user_account.id
	 *
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_account.id
	 *
	 * @param id
	 *            the value for user_account.id
	 *
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_account.name
	 *
	 * @return the value of user_account.name
	 *
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_account.name
	 *
	 * @param name
	 *            the value for user_account.name
	 *
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_account.nick_name
	 *
	 * @return the value of user_account.nick_name
	 *
	 * @mbggenerated
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_account.nick_name
	 *
	 * @param nickName
	 *            the value for user_account.nick_name
	 *
	 * @mbggenerated
	 */
	public void setNickName(String nickName) {
		this.nickName = nickName == null ? null : nickName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_account.user_password
	 *
	 * @return the value of user_account.user_password
	 *
	 * @mbggenerated
	 */
	public String getUserPassword() {
		return userPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_account.user_password
	 *
	 * @param userPassword
	 *            the value for user_account.user_password
	 *
	 * @mbggenerated
	 */
	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword == null ? null : userPassword.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_account.update_time
	 *
	 * @return the value of user_account.update_time
	 *
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_account.update_time
	 *
	 * @param updateTime
	 *            the value for user_account.update_time
	 *
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_account.create_time
	 *
	 * @return the value of user_account.create_time
	 *
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_account.create_time
	 *
	 * @param createTime
	 *            the value for user_account.create_time
	 *
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_account.user_type
	 *
	 * @return the value of user_account.user_type
	 *
	 * @mbggenerated
	 */
	public Integer getUserType() {
		return userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_account.user_type
	 *
	 * @param userType
	 *            the value for user_account.user_type
	 *
	 * @mbggenerated
	 */
	public void setUserType(Integer userType) {
		this.userType = userType;
	}

	public Map<PropertyTypes, UserExtra> getPropertiesAsMap() {
		Map<PropertyTypes, UserExtra> map = null;
		if (properties != null) {
			map = GameUtil.getMap();
			for (UserExtra extra : properties) {
				if (extra.getProperty() != null)
					map.put(extra.getProperty().getName(), extra);
			}
		}
		return map;
	}

	public List<UserItems> getItems() {
		return items;
	}

	public void setItems(List<UserItems> items) {
		this.items = items;
	}
	
	
	public Map<ItemTypes,UserItems> getItemsAsMap(){
		Map<ItemTypes,UserItems> map=null;
		if(items!=null){
			map=GameUtil.getMap();
			for(UserItems item:items){
				
					ItemTypes types=ItemTypes.getItemTypes(item.getItemId().intValue());
					if(!types.eq(ItemTypes.Undefined)){
						map.put(types, item);
					}
					
				
			}
		}
		return map;
	}
	
	private long channelId;
    private String deviceId;
	public long getChannelId() {
		return channelId;
	}

	public void setChannelId(long channelId) {
		this.channelId = channelId;
	}
	public String getDeviceId() {
		return deviceId;
	}
	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

}