package com.sky.game.service.domain;

import java.util.Date;

public class UserItemLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_item_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_item_log.user_account_id
     *
     * @mbggenerated
     */
    private Long userAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_item_log.item_id
     *
     * @mbggenerated
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_item_log.item_value
     *
     * @mbggenerated
     */
    private Integer itemValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_item_log.value
     *
     * @mbggenerated
     */
    private Integer value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_item_log.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_item_log.resum_type
     *
     * @mbggenerated
     */
    private String resumType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_item_log.id
     *
     * @return the value of user_item_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_item_log.id
     *
     * @param id the value for user_item_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_item_log.user_account_id
     *
     * @return the value of user_item_log.user_account_id
     *
     * @mbggenerated
     */
    public Long getUserAccountId() {
        return userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_item_log.user_account_id
     *
     * @param userAccountId the value for user_item_log.user_account_id
     *
     * @mbggenerated
     */
    public void setUserAccountId(Long userAccountId) {
        this.userAccountId = userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_item_log.item_id
     *
     * @return the value of user_item_log.item_id
     *
     * @mbggenerated
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_item_log.item_id
     *
     * @param itemId the value for user_item_log.item_id
     *
     * @mbggenerated
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_item_log.item_value
     *
     * @return the value of user_item_log.item_value
     *
     * @mbggenerated
     */
    public Integer getItemValue() {
        return itemValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_item_log.item_value
     *
     * @param itemValue the value for user_item_log.item_value
     *
     * @mbggenerated
     */
    public void setItemValue(Integer itemValue) {
        this.itemValue = itemValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_item_log.value
     *
     * @return the value of user_item_log.value
     *
     * @mbggenerated
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_item_log.value
     *
     * @param value the value for user_item_log.value
     *
     * @mbggenerated
     */
    public void setValue(Integer value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_item_log.update_time
     *
     * @return the value of user_item_log.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_item_log.update_time
     *
     * @param updateTime the value for user_item_log.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_item_log.resum_type
     *
     * @return the value of user_item_log.resum_type
     *
     * @mbggenerated
     */
    public String getResumType() {
        return resumType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_item_log.resum_type
     *
     * @param resumType the value for user_item_log.resum_type
     *
     * @mbggenerated
     */
    public void setResumType(String resumType) {
        this.resumType = resumType == null ? null : resumType.trim();
    }
}