package com.sky.game.service.domain;

import java.util.Date;

public class UserVip {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_vip.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_vip.user_account_id
     *
     * @mbggenerated
     */
    private Long userAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_vip.vip_start_time
     *
     * @mbggenerated
     */
    private Date vipStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_vip.vip_end_time
     *
     * @mbggenerated
     */
    private Date vipEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_vip.vip_point
     *
     * @mbggenerated
     */
    private Integer vipPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_vip.vip_level
     *
     * @mbggenerated
     */
    private Integer vipLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_vip.id
     *
     * @return the value of user_vip.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_vip.id
     *
     * @param id the value for user_vip.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_vip.user_account_id
     *
     * @return the value of user_vip.user_account_id
     *
     * @mbggenerated
     */
    public Long getUserAccountId() {
        return userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_vip.user_account_id
     *
     * @param userAccountId the value for user_vip.user_account_id
     *
     * @mbggenerated
     */
    public void setUserAccountId(Long userAccountId) {
        this.userAccountId = userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_vip.vip_start_time
     *
     * @return the value of user_vip.vip_start_time
     *
     * @mbggenerated
     */
    public Date getVipStartTime() {
        return vipStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_vip.vip_start_time
     *
     * @param vipStartTime the value for user_vip.vip_start_time
     *
     * @mbggenerated
     */
    public void setVipStartTime(Date vipStartTime) {
        this.vipStartTime = vipStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_vip.vip_end_time
     *
     * @return the value of user_vip.vip_end_time
     *
     * @mbggenerated
     */
    public Date getVipEndTime() {
        return vipEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_vip.vip_end_time
     *
     * @param vipEndTime the value for user_vip.vip_end_time
     *
     * @mbggenerated
     */
    public void setVipEndTime(Date vipEndTime) {
        this.vipEndTime = vipEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_vip.vip_point
     *
     * @return the value of user_vip.vip_point
     *
     * @mbggenerated
     */
    public Integer getVipPoint() {
        return vipPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_vip.vip_point
     *
     * @param vipPoint the value for user_vip.vip_point
     *
     * @mbggenerated
     */
    public void setVipPoint(Integer vipPoint) {
        this.vipPoint = vipPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_vip.vip_level
     *
     * @return the value of user_vip.vip_level
     *
     * @mbggenerated
     */
    public Integer getVipLevel() {
        return vipLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_vip.vip_level
     *
     * @param vipLevel the value for user_vip.vip_level
     *
     * @mbggenerated
     */
    public void setVipLevel(Integer vipLevel) {
        this.vipLevel = vipLevel;
    }
}