package com.sky.game.service.domain;

import java.util.Date;

public class UserReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_report.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_report.user_account_id
     *
     * @mbggenerated
     */
    private Long userAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_report.last_date
     *
     * @mbggenerated
     */
    private Date lastDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_report.continuous_days
     *
     * @mbggenerated
     */
    private Integer continuousDays;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_report.id
     *
     * @return the value of user_report.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_report.id
     *
     * @param id the value for user_report.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_report.user_account_id
     *
     * @return the value of user_report.user_account_id
     *
     * @mbggenerated
     */
    public Long getUserAccountId() {
        return userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_report.user_account_id
     *
     * @param userAccountId the value for user_report.user_account_id
     *
     * @mbggenerated
     */
    public void setUserAccountId(Long userAccountId) {
        this.userAccountId = userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_report.last_date
     *
     * @return the value of user_report.last_date
     *
     * @mbggenerated
     */
    public Date getLastDate() {
        return lastDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_report.last_date
     *
     * @param lastDate the value for user_report.last_date
     *
     * @mbggenerated
     */
    public void setLastDate(Date lastDate) {
        this.lastDate = lastDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_report.continuous_days
     *
     * @return the value of user_report.continuous_days
     *
     * @mbggenerated
     */
    public Integer getContinuousDays() {
        return continuousDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_report.continuous_days
     *
     * @param continuousDays the value for user_report.continuous_days
     *
     * @mbggenerated
     */
    public void setContinuousDays(Integer continuousDays) {
        this.continuousDays = continuousDays;
    }
}