package com.sky.game.service.domain;

import java.util.Date;

public class UserReward {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_reward.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_reward.user_account_id
     *
     * @mbggenerated
     */
    private Long userAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_reward.reward_id
     *
     * @mbggenerated
     */
    private Long rewardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_reward.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_reward.gain_time
     *
     * @mbggenerated
     */
    private Date gainTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_reward.rank
     *
     * @mbggenerated
     */
    private String rank;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reward.id
     *
     * @return the value of user_reward.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reward.id
     *
     * @param id the value for user_reward.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reward.user_account_id
     *
     * @return the value of user_reward.user_account_id
     *
     * @mbggenerated
     */
    public Long getUserAccountId() {
        return userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reward.user_account_id
     *
     * @param userAccountId the value for user_reward.user_account_id
     *
     * @mbggenerated
     */
    public void setUserAccountId(Long userAccountId) {
        this.userAccountId = userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reward.reward_id
     *
     * @return the value of user_reward.reward_id
     *
     * @mbggenerated
     */
    public Long getRewardId() {
        return rewardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reward.reward_id
     *
     * @param rewardId the value for user_reward.reward_id
     *
     * @mbggenerated
     */
    public void setRewardId(Long rewardId) {
        this.rewardId = rewardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reward.state
     *
     * @return the value of user_reward.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reward.state
     *
     * @param state the value for user_reward.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reward.gain_time
     *
     * @return the value of user_reward.gain_time
     *
     * @mbggenerated
     */
    public Date getGainTime() {
        return gainTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reward.gain_time
     *
     * @param gainTime the value for user_reward.gain_time
     *
     * @mbggenerated
     */
    public void setGainTime(Date gainTime) {
        this.gainTime = gainTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reward.rank
     *
     * @return the value of user_reward.rank
     *
     * @mbggenerated
     */
    public String getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reward.rank
     *
     * @param rank the value for user_reward.rank
     *
     * @mbggenerated
     */
    public void setRank(String rank) {
        this.rank = rank == null ? null : rank.trim();
    }
}